//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polizas
    {
        public int idPoliza { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string tipoCubrimiento { get; set; }
        public Nullable<int> Cobertura { get; set; }
        public Nullable<System.DateTime> inicioVigencia { get; set; }
        public Nullable<int> periodoCobertura { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string tipoRiesgo { get; set; }
    }
}
